"""Load Walmart.csv into SQLite, run the SQL scripts, and save every result to query_results.md.

Usage (from the repo root):  python sql/run_sql.py
"""
import csv
import math
import re
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SQL_DIR = ROOT / "sql"

con = sqlite3.connect(ROOT / "sql" / "walmart.db")
con.create_function("SQRT", 1, math.sqrt)  # older SQLite builds lack SQRT

con.executescript((SQL_DIR / "01_create_and_clean.sql").read_text().split("-- 3. Data-quality")[0])
with open(ROOT / "Walmart.csv", newline="") as fh:
    rows = list(csv.reader(fh))[1:]
con.executemany("INSERT INTO walmart_raw VALUES (?,?,?,?,?,?,?,?)", rows)
con.commit()


def to_markdown(cur):
    cols = [c[0] for c in cur.description]
    out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for r in cur.fetchall():
        out.append("| " + " | ".join("" if v is None else str(v) for v in r) + " |")
    return "\n".join(out)


report = ["# Query results\n", "Generated by `sql/run_sql.py` against `Walmart.csv`.\n"]

dq = "-- 3. Data-quality" + (SQL_DIR / "01_create_and_clean.sql").read_text().split("-- 3. Data-quality")[1]
report += ["## Data-quality checks\n", to_markdown(con.execute(dq.split("\n", 2)[2])), ""]

blocks = re.split(r"^-- @(Q\d+) ", (SQL_DIR / "02_business_questions.sql").read_text(), flags=re.M)
for qid, body in zip(blocks[1::2], blocks[2::2]):
    title = body.splitlines()[0].strip()
    report += [f"## {qid}. {title}\n", to_markdown(con.execute(body.split("\n", 1)[1])), ""]

(SQL_DIR / "query_results.md").write_text("\n".join(report))
print("Saved sql/query_results.md")
